### ISSUE TITLE
Slow to update value in skynet

### ISSUE THREAD

**Issue by Fluffy9** [Fluffy9/Zenbase#1]
Had a discussion on discord about this. I decided to make an issue here to keep track: 

> It works, but the db is not so reactive - have to refresh the page because data doesn't come to .on() from skynet easily
> but eventually it's there

I'm unsure where this problem is coming from. It would either be my code or something more deeply Skynet related. My first guess is that there is latency coming from the Skynet portal. There will be limited workarounds if the issue comes from a portal. The technology is new so I could contact the team and it could just fix itself over time. Otherwise, I could: 

* automatically switch to a backup portal
* throw an error or something instead of returning stale data

I'll do some debugging and hopefully fix this soon

**Comment by Fluffy9** [comment]
Turns out that Skynet is (likely) the source of the delay. I've been told they are working on this issue, but I may also make some changes in how frequently data is saved to Skynet

**Comment by CardxCoin** [comment]
Turns out the delay is coming from Skynet. Apparently GunDB writes to storage in quarter second intervals, which is faster than Skynet can handle. This is something being worked on, but a temporary fix would be increasing the batch times when initializing Gun. Changing this setting could cause further issues down the line and Sia is working on fixing the issue, so I don't want to make an update to Zenbase's source code. I'll just make mention of this in the readme

**Comment by Fluffy9** [comment]
I've found a workaround for this issue. By changing the settings in Gun, we can change how frequently data is written to storage (default is 4 times a second). This should provide some improvements but it could also result in unforeseen consequences. Sia is working on fixing this issue on their side so this should be good enough.
